### ISSUE TITLE
no differentiation between inner and outer rings

### ISSUE THREAD

**Issue by riccardoklinger** [Geolicious/OSMroute#1]
currently I don't get any inner plygons and also there is no difference when selecting for 5 intervals or just 1...

**Comment by ghost** [comment]
please also see issue here for further explanation since we offer two methods for computing isochrones "RecursiveGrid" and "TIN" + Polygon Preference Parameter.

https://github.com/GIScience/openrouteservice/issues/40

Example request below and the service response provide exterior and interior rings
<?xml version="1.0" encoding="UTF-8" ?>
<aas:AAS version="1.0" xmlns:aas="http://www.geoinform.fh-mainz.de/aas" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.geoinform.fh-mainz.de/aas">
    aas:RequestHeader
    /aas:RequestHeader
    <aas:Request methodName="AccessibilityRequest" version="1.0" requestID="00">
        aas:DetermineAccessibilityRequest
            aas:Accessibility
                aas:AccessibilityPreference
                    <aas:Time Duration="PT0H15M00S" />
                /aas:AccessibilityPreference
                aas:AccessibilitySettings
                    aas:RoutePreferenceCar/aas:RoutePreference
                    aas:MethodRecursiveGrid/aas:Method
                    aas:Interval180/aas:Interval
                /aas:AccessibilitySettings
                aas:LocationPoint
                    aas:Position
                        <gml:Point xmlns:gml="http://www.opengis.net/gml" srsName="EPSG:4326">
                            gml:pos8.651239285400413 49.40793714414487/gml:pos
                        /gml:Point
                    /aas:Position
                /aas:LocationPoint
            /aas:Accessibility
            aas:AccessibilityGeometryRequest
                aas:PolygonPreferenceDetailed/aas:PolygonPreference
            /aas:AccessibilityGeometryRequest
        /aas:DetermineAccessibilityRequest
    /aas:Request
/aas:AAS

**Comment by riccardoklinger** [comment]
I have used the wrong paramter for intervalls. now its working.
